### ISSUE TITLE
cursor movement on mac with META+[SHIFT]+ARROW

### ISSUE THREAD

**Issue by bantic** [bustlelabs/mobiledoc-kit#383]
As a follow-on to https://github.com/bustlelabs/mobiledoc-kit/pull/380.
A few cursor-movement commands need to be implemented for Mac:

  * [ ] <kbd>command</kbd> + UP/DOWN — moves cursor to start/end of the post, respectively
  * [ ] <kbd>command</kbd><kbd>shift</kbd> + UP/DOWN — moves the head/tail of the range to the start/end of the post, respectively
  * [ ] <kbd>command</kbd><kbd>shift</kbd> + LEFT/RIGHT — moves the head/tail of the range to the start/end of the section, respectively

**Comment by bantic** [comment]
cc @atonse If you are interested, PRs for any of these would be happily accepted

**Comment by cknific** [comment]
I noticed this issue today: 
With your cursor on line 1, hit CMD+DownArrow to go to the bottom of the editor. Start typing. The cursor jumps back to where you were on Line 1.
![example](https://cloud.githubusercontent.com/assets/903898/15304143/8f1e05e8-1b70-11e6-8f8a-1baa7b704424.gif)

**Comment by lessless** [comment]
PR for the later https://github.com/bustlelabs/mobiledoc-kit/pull/403/files
It mostly consists of c&p code, so any improvement suggestions are very welcome!

**Comment by lessless** [comment]
@cknific can you please open separate issue for that bug? I'm afraid it can loose and don't get deserved attention.

**Comment by bantic** [comment]
fixed in [v0.10.0](https://github.com/bustlelabs/mobiledoc-kit/releases/tag/v0.10.0)
